Output demo.gif

Set Shell "bash"
Set FontSize 24
Set Width 2560
Set Height 1440

Type "go run main.go"

Sleep 2s

Enter

Sleep 2s

Type "p"

Sleep 2s

Down@200ms 4

Sleep 2s

Enter

Sleep 2s

Backspace@200ms 4

Sleep 2s

Type "1920"

Sleep 2s

Down

Backspace@200ms 4

Sleep 2s

Type "1080"

Sleep 2s

Down

Sleep 2s

Down

Sleep 2s

Enter

Sleep 2s

Up

Sleep 2s

Enter

Sleep 2s

Down

Sleep 2s

Down

Sleep 2s

Enter

Sleep 2s

Down

Sleep 2s

Enter

Sleep 5s
